default_db: crypto
connection_string: "mongodb://192.168.31.218:27017"
username: ""
password: ""

db_name:
  crypto: "crypto"
  cn_share: "cn_share"
  us_share: "us_share"
  hk_share: "hk_share"
  fund: "fund"
  option: "option"
  future: "future"
